name: "Self Delete Workflow"
description: "An action that deletes the workflow that launches it"
author: "mail@fabriziocacicia.com"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Workflow Path
      id: get_workflow_path
      shell: bash
      run: |
        IFS='@'
        read -a strarr <<< "$GITHUB_WORKFLOW_REF"
        workflow_ref=${strarr[0]}
        workflow_path=${workflow_ref#"$GITHUB_REPOSITORY/"}
        
        echo "value=$workflow_path" >> $GITHUB_OUTPUT
    - name: Delete Workflow
      shell: bash
      run: |
        rm '${{ steps.get_workflow_path.outputs.value }}'
    - name: Push Changes
      uses: fabriziocacicia/commit-and-push-to-protected-branch-action@v0.2.0
      with:
        git_user_name: "Self Delete Workflow Github Action"
        temp_branch_prefix: "self_delete"
        commit_message: "chore: remove the ${{ steps.get_workflow_path.outputs.value }} workflow"
